name: Publish Release

on:
  push:
    tags:
      - 'v*' # This triggers the workflow when you push a tag like 'v1.0.1'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t ./lib --upgrade

      - name: Build zip
        run: |
          Compress-Archive -Path * -DestinationPath Ai-Assistant.zip -Force

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "Ai-Assistant.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
